// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CommandMotorSpeed.proto

#include "CommandMotorSpeed.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
namespace mav_msgs {
namespace msgs {
class CommandMotorSpeedDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<CommandMotorSpeed> _instance;
} _CommandMotorSpeed_default_instance_;
}  // namespace msgs
}  // namespace mav_msgs
static void InitDefaultsscc_info_CommandMotorSpeed_CommandMotorSpeed_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::mav_msgs::msgs::_CommandMotorSpeed_default_instance_;
    new (ptr) ::mav_msgs::msgs::CommandMotorSpeed();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::mav_msgs::msgs::CommandMotorSpeed::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_CommandMotorSpeed_CommandMotorSpeed_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_CommandMotorSpeed_CommandMotorSpeed_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_CommandMotorSpeed_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_CommandMotorSpeed_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_CommandMotorSpeed_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_CommandMotorSpeed_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::mav_msgs::msgs::CommandMotorSpeed, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::mav_msgs::msgs::CommandMotorSpeed, motor_speed_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::mav_msgs::msgs::CommandMotorSpeed)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::mav_msgs::msgs::_CommandMotorSpeed_default_instance_),
};

const char descriptor_table_protodef_CommandMotorSpeed_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\027CommandMotorSpeed.proto\022\rmav_msgs.msgs"
  "\",\n\021CommandMotorSpeed\022\027\n\013motor_speed\030\001 \003"
  "(\002B\002\020\001"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_CommandMotorSpeed_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_CommandMotorSpeed_2eproto_sccs[1] = {
  &scc_info_CommandMotorSpeed_CommandMotorSpeed_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_CommandMotorSpeed_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_CommandMotorSpeed_2eproto = {
  false, false, descriptor_table_protodef_CommandMotorSpeed_2eproto, "CommandMotorSpeed.proto", 86,
  &descriptor_table_CommandMotorSpeed_2eproto_once, descriptor_table_CommandMotorSpeed_2eproto_sccs, descriptor_table_CommandMotorSpeed_2eproto_deps, 1, 0,
  schemas, file_default_instances, TableStruct_CommandMotorSpeed_2eproto::offsets,
  file_level_metadata_CommandMotorSpeed_2eproto, 1, file_level_enum_descriptors_CommandMotorSpeed_2eproto, file_level_service_descriptors_CommandMotorSpeed_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_CommandMotorSpeed_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_CommandMotorSpeed_2eproto)), true);
namespace mav_msgs {
namespace msgs {

// ===================================================================

void CommandMotorSpeed::InitAsDefaultInstance() {
}
class CommandMotorSpeed::_Internal {
 public:
};

CommandMotorSpeed::CommandMotorSpeed(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena),
  motor_speed_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:mav_msgs.msgs.CommandMotorSpeed)
}
CommandMotorSpeed::CommandMotorSpeed(const CommandMotorSpeed& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      motor_speed_(from.motor_speed_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:mav_msgs.msgs.CommandMotorSpeed)
}

void CommandMotorSpeed::SharedCtor() {
}

CommandMotorSpeed::~CommandMotorSpeed() {
  // @@protoc_insertion_point(destructor:mav_msgs.msgs.CommandMotorSpeed)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void CommandMotorSpeed::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void CommandMotorSpeed::ArenaDtor(void* object) {
  CommandMotorSpeed* _this = reinterpret_cast< CommandMotorSpeed* >(object);
  (void)_this;
}
void CommandMotorSpeed::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void CommandMotorSpeed::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const CommandMotorSpeed& CommandMotorSpeed::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_CommandMotorSpeed_CommandMotorSpeed_2eproto.base);
  return *internal_default_instance();
}


void CommandMotorSpeed::Clear() {
// @@protoc_insertion_point(message_clear_start:mav_msgs.msgs.CommandMotorSpeed)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  motor_speed_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* CommandMotorSpeed::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // repeated float motor_speed = 1 [packed = true];
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedFloatParser(_internal_mutable_motor_speed(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 13) {
          _internal_add_motor_speed(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr));
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* CommandMotorSpeed::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:mav_msgs.msgs.CommandMotorSpeed)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated float motor_speed = 1 [packed = true];
  if (this->_internal_motor_speed_size() > 0) {
    target = stream->WriteFixedPacked(1, _internal_motor_speed(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:mav_msgs.msgs.CommandMotorSpeed)
  return target;
}

size_t CommandMotorSpeed::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:mav_msgs.msgs.CommandMotorSpeed)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated float motor_speed = 1 [packed = true];
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_motor_speed_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<::PROTOBUF_NAMESPACE_ID::int32>(data_size));
    }
    int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(data_size);
    _motor_speed_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void CommandMotorSpeed::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:mav_msgs.msgs.CommandMotorSpeed)
  GOOGLE_DCHECK_NE(&from, this);
  const CommandMotorSpeed* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<CommandMotorSpeed>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:mav_msgs.msgs.CommandMotorSpeed)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:mav_msgs.msgs.CommandMotorSpeed)
    MergeFrom(*source);
  }
}

void CommandMotorSpeed::MergeFrom(const CommandMotorSpeed& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:mav_msgs.msgs.CommandMotorSpeed)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  motor_speed_.MergeFrom(from.motor_speed_);
}

void CommandMotorSpeed::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:mav_msgs.msgs.CommandMotorSpeed)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CommandMotorSpeed::CopyFrom(const CommandMotorSpeed& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:mav_msgs.msgs.CommandMotorSpeed)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CommandMotorSpeed::IsInitialized() const {
  return true;
}

void CommandMotorSpeed::InternalSwap(CommandMotorSpeed* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  motor_speed_.InternalSwap(&other->motor_speed_);
}

::PROTOBUF_NAMESPACE_ID::Metadata CommandMotorSpeed::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace msgs
}  // namespace mav_msgs
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::mav_msgs::msgs::CommandMotorSpeed* Arena::CreateMaybeMessage< ::mav_msgs::msgs::CommandMotorSpeed >(Arena* arena) {
  return Arena::CreateMessageInternal< ::mav_msgs::msgs::CommandMotorSpeed >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
