// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Force.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_Force_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_Force_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "vector3d.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_Force_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_Force_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Force_2eproto;
namespace physics_msgs {
namespace msgs {
class Force;
class ForceDefaultTypeInternal;
extern ForceDefaultTypeInternal _Force_default_instance_;
}  // namespace msgs
}  // namespace physics_msgs
PROTOBUF_NAMESPACE_OPEN
template<> ::physics_msgs::msgs::Force* Arena::CreateMaybeMessage<::physics_msgs::msgs::Force>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace physics_msgs {
namespace msgs {

// ===================================================================

class Force PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:physics_msgs.msgs.Force) */ {
 public:
  inline Force() : Force(nullptr) {};
  virtual ~Force();

  Force(const Force& from);
  Force(Force&& from) noexcept
    : Force() {
    *this = ::std::move(from);
  }

  inline Force& operator=(const Force& from) {
    CopyFrom(from);
    return *this;
  }
  inline Force& operator=(Force&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Force& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Force* internal_default_instance() {
    return reinterpret_cast<const Force*>(
               &_Force_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Force& a, Force& b) {
    a.Swap(&b);
  }
  inline void Swap(Force* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Force* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Force* New() const final {
    return CreateMaybeMessage<Force>(nullptr);
  }

  Force* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Force>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Force& from);
  void MergeFrom(const Force& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Force* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "physics_msgs.msgs.Force";
  }
  protected:
  explicit Force(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_Force_2eproto);
    return ::descriptor_table_Force_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kCenterFieldNumber = 1,
    kForceFieldNumber = 2,
  };
  // required .gazebo.msgs.Vector3d center = 1;
  bool has_center() const;
  private:
  bool _internal_has_center() const;
  public:
  void clear_center();
  const ::gazebo::msgs::Vector3d& center() const;
  ::gazebo::msgs::Vector3d* release_center();
  ::gazebo::msgs::Vector3d* mutable_center();
  void set_allocated_center(::gazebo::msgs::Vector3d* center);
  private:
  const ::gazebo::msgs::Vector3d& _internal_center() const;
  ::gazebo::msgs::Vector3d* _internal_mutable_center();
  public:
  void unsafe_arena_set_allocated_center(
      ::gazebo::msgs::Vector3d* center);
  ::gazebo::msgs::Vector3d* unsafe_arena_release_center();

  // required .gazebo.msgs.Vector3d force = 2;
  bool has_force() const;
  private:
  bool _internal_has_force() const;
  public:
  void clear_force();
  const ::gazebo::msgs::Vector3d& force() const;
  ::gazebo::msgs::Vector3d* release_force();
  ::gazebo::msgs::Vector3d* mutable_force();
  void set_allocated_force(::gazebo::msgs::Vector3d* force);
  private:
  const ::gazebo::msgs::Vector3d& _internal_force() const;
  ::gazebo::msgs::Vector3d* _internal_mutable_force();
  public:
  void unsafe_arena_set_allocated_force(
      ::gazebo::msgs::Vector3d* force);
  ::gazebo::msgs::Vector3d* unsafe_arena_release_force();

  // @@protoc_insertion_point(class_scope:physics_msgs.msgs.Force)
 private:
  class _Internal;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::gazebo::msgs::Vector3d* center_;
  ::gazebo::msgs::Vector3d* force_;
  friend struct ::TableStruct_Force_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Force

// required .gazebo.msgs.Vector3d center = 1;
inline bool Force::_internal_has_center() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || center_ != nullptr);
  return value;
}
inline bool Force::has_center() const {
  return _internal_has_center();
}
inline const ::gazebo::msgs::Vector3d& Force::_internal_center() const {
  const ::gazebo::msgs::Vector3d* p = center_;
  return p != nullptr ? *p : *reinterpret_cast<const ::gazebo::msgs::Vector3d*>(
      &::gazebo::msgs::_Vector3d_default_instance_);
}
inline const ::gazebo::msgs::Vector3d& Force::center() const {
  // @@protoc_insertion_point(field_get:physics_msgs.msgs.Force.center)
  return _internal_center();
}
inline void Force::unsafe_arena_set_allocated_center(
    ::gazebo::msgs::Vector3d* center) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(center_);
  }
  center_ = center;
  if (center) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:physics_msgs.msgs.Force.center)
}
inline ::gazebo::msgs::Vector3d* Force::release_center() {
  auto temp = unsafe_arena_release_center();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::gazebo::msgs::Vector3d* Force::unsafe_arena_release_center() {
  // @@protoc_insertion_point(field_release:physics_msgs.msgs.Force.center)
  _has_bits_[0] &= ~0x00000001u;
  ::gazebo::msgs::Vector3d* temp = center_;
  center_ = nullptr;
  return temp;
}
inline ::gazebo::msgs::Vector3d* Force::_internal_mutable_center() {
  _has_bits_[0] |= 0x00000001u;
  if (center_ == nullptr) {
    auto* p = CreateMaybeMessage<::gazebo::msgs::Vector3d>(GetArena());
    center_ = p;
  }
  return center_;
}
inline ::gazebo::msgs::Vector3d* Force::mutable_center() {
  // @@protoc_insertion_point(field_mutable:physics_msgs.msgs.Force.center)
  return _internal_mutable_center();
}
inline void Force::set_allocated_center(::gazebo::msgs::Vector3d* center) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(center_);
  }
  if (center) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(center)->GetArena();
    if (message_arena != submessage_arena) {
      center = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, center, submessage_arena);
    }
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  center_ = center;
  // @@protoc_insertion_point(field_set_allocated:physics_msgs.msgs.Force.center)
}

// required .gazebo.msgs.Vector3d force = 2;
inline bool Force::_internal_has_force() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || force_ != nullptr);
  return value;
}
inline bool Force::has_force() const {
  return _internal_has_force();
}
inline const ::gazebo::msgs::Vector3d& Force::_internal_force() const {
  const ::gazebo::msgs::Vector3d* p = force_;
  return p != nullptr ? *p : *reinterpret_cast<const ::gazebo::msgs::Vector3d*>(
      &::gazebo::msgs::_Vector3d_default_instance_);
}
inline const ::gazebo::msgs::Vector3d& Force::force() const {
  // @@protoc_insertion_point(field_get:physics_msgs.msgs.Force.force)
  return _internal_force();
}
inline void Force::unsafe_arena_set_allocated_force(
    ::gazebo::msgs::Vector3d* force) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(force_);
  }
  force_ = force;
  if (force) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:physics_msgs.msgs.Force.force)
}
inline ::gazebo::msgs::Vector3d* Force::release_force() {
  auto temp = unsafe_arena_release_force();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::gazebo::msgs::Vector3d* Force::unsafe_arena_release_force() {
  // @@protoc_insertion_point(field_release:physics_msgs.msgs.Force.force)
  _has_bits_[0] &= ~0x00000002u;
  ::gazebo::msgs::Vector3d* temp = force_;
  force_ = nullptr;
  return temp;
}
inline ::gazebo::msgs::Vector3d* Force::_internal_mutable_force() {
  _has_bits_[0] |= 0x00000002u;
  if (force_ == nullptr) {
    auto* p = CreateMaybeMessage<::gazebo::msgs::Vector3d>(GetArena());
    force_ = p;
  }
  return force_;
}
inline ::gazebo::msgs::Vector3d* Force::mutable_force() {
  // @@protoc_insertion_point(field_mutable:physics_msgs.msgs.Force.force)
  return _internal_mutable_force();
}
inline void Force::set_allocated_force(::gazebo::msgs::Vector3d* force) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(force_);
  }
  if (force) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(force)->GetArena();
    if (message_arena != submessage_arena) {
      force = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, force, submessage_arena);
    }
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  force_ = force;
  // @@protoc_insertion_point(field_set_allocated:physics_msgs.msgs.Force.force)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace msgs
}  // namespace physics_msgs

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_Force_2eproto
