// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Imu.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_Imu_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_Imu_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "quaternion.pb.h"
#include "vector3d.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_Imu_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_Imu_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Imu_2eproto;
namespace sensor_msgs {
namespace msgs {
class Imu;
class ImuDefaultTypeInternal;
extern ImuDefaultTypeInternal _Imu_default_instance_;
}  // namespace msgs
}  // namespace sensor_msgs
PROTOBUF_NAMESPACE_OPEN
template<> ::sensor_msgs::msgs::Imu* Arena::CreateMaybeMessage<::sensor_msgs::msgs::Imu>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace sensor_msgs {
namespace msgs {

// ===================================================================

class Imu PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:sensor_msgs.msgs.Imu) */ {
 public:
  inline Imu() : Imu(nullptr) {};
  virtual ~Imu();

  Imu(const Imu& from);
  Imu(Imu&& from) noexcept
    : Imu() {
    *this = ::std::move(from);
  }

  inline Imu& operator=(const Imu& from) {
    CopyFrom(from);
    return *this;
  }
  inline Imu& operator=(Imu&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Imu& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Imu* internal_default_instance() {
    return reinterpret_cast<const Imu*>(
               &_Imu_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Imu& a, Imu& b) {
    a.Swap(&b);
  }
  inline void Swap(Imu* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Imu* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Imu* New() const final {
    return CreateMaybeMessage<Imu>(nullptr);
  }

  Imu* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Imu>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Imu& from);
  void MergeFrom(const Imu& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Imu* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "sensor_msgs.msgs.Imu";
  }
  protected:
  explicit Imu(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_Imu_2eproto);
    return ::descriptor_table_Imu_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kOrientationCovarianceFieldNumber = 2,
    kAngularVelocityCovarianceFieldNumber = 4,
    kLinearAccelerationCovarianceFieldNumber = 6,
    kOrientationFieldNumber = 1,
    kAngularVelocityFieldNumber = 3,
    kLinearAccelerationFieldNumber = 5,
    kTimeUsecFieldNumber = 7,
    kSeqFieldNumber = 8,
  };
  // repeated float orientation_covariance = 2 [packed = true];
  int orientation_covariance_size() const;
  private:
  int _internal_orientation_covariance_size() const;
  public:
  void clear_orientation_covariance();
  private:
  float _internal_orientation_covariance(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      _internal_orientation_covariance() const;
  void _internal_add_orientation_covariance(float value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      _internal_mutable_orientation_covariance();
  public:
  float orientation_covariance(int index) const;
  void set_orientation_covariance(int index, float value);
  void add_orientation_covariance(float value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      orientation_covariance() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      mutable_orientation_covariance();

  // repeated float angular_velocity_covariance = 4 [packed = true];
  int angular_velocity_covariance_size() const;
  private:
  int _internal_angular_velocity_covariance_size() const;
  public:
  void clear_angular_velocity_covariance();
  private:
  float _internal_angular_velocity_covariance(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      _internal_angular_velocity_covariance() const;
  void _internal_add_angular_velocity_covariance(float value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      _internal_mutable_angular_velocity_covariance();
  public:
  float angular_velocity_covariance(int index) const;
  void set_angular_velocity_covariance(int index, float value);
  void add_angular_velocity_covariance(float value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      angular_velocity_covariance() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      mutable_angular_velocity_covariance();

  // repeated float linear_acceleration_covariance = 6 [packed = true];
  int linear_acceleration_covariance_size() const;
  private:
  int _internal_linear_acceleration_covariance_size() const;
  public:
  void clear_linear_acceleration_covariance();
  private:
  float _internal_linear_acceleration_covariance(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      _internal_linear_acceleration_covariance() const;
  void _internal_add_linear_acceleration_covariance(float value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      _internal_mutable_linear_acceleration_covariance();
  public:
  float linear_acceleration_covariance(int index) const;
  void set_linear_acceleration_covariance(int index, float value);
  void add_linear_acceleration_covariance(float value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      linear_acceleration_covariance() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      mutable_linear_acceleration_covariance();

  // required .gazebo.msgs.Quaternion orientation = 1;
  bool has_orientation() const;
  private:
  bool _internal_has_orientation() const;
  public:
  void clear_orientation();
  const ::gazebo::msgs::Quaternion& orientation() const;
  ::gazebo::msgs::Quaternion* release_orientation();
  ::gazebo::msgs::Quaternion* mutable_orientation();
  void set_allocated_orientation(::gazebo::msgs::Quaternion* orientation);
  private:
  const ::gazebo::msgs::Quaternion& _internal_orientation() const;
  ::gazebo::msgs::Quaternion* _internal_mutable_orientation();
  public:
  void unsafe_arena_set_allocated_orientation(
      ::gazebo::msgs::Quaternion* orientation);
  ::gazebo::msgs::Quaternion* unsafe_arena_release_orientation();

  // required .gazebo.msgs.Vector3d angular_velocity = 3;
  bool has_angular_velocity() const;
  private:
  bool _internal_has_angular_velocity() const;
  public:
  void clear_angular_velocity();
  const ::gazebo::msgs::Vector3d& angular_velocity() const;
  ::gazebo::msgs::Vector3d* release_angular_velocity();
  ::gazebo::msgs::Vector3d* mutable_angular_velocity();
  void set_allocated_angular_velocity(::gazebo::msgs::Vector3d* angular_velocity);
  private:
  const ::gazebo::msgs::Vector3d& _internal_angular_velocity() const;
  ::gazebo::msgs::Vector3d* _internal_mutable_angular_velocity();
  public:
  void unsafe_arena_set_allocated_angular_velocity(
      ::gazebo::msgs::Vector3d* angular_velocity);
  ::gazebo::msgs::Vector3d* unsafe_arena_release_angular_velocity();

  // required .gazebo.msgs.Vector3d linear_acceleration = 5;
  bool has_linear_acceleration() const;
  private:
  bool _internal_has_linear_acceleration() const;
  public:
  void clear_linear_acceleration();
  const ::gazebo::msgs::Vector3d& linear_acceleration() const;
  ::gazebo::msgs::Vector3d* release_linear_acceleration();
  ::gazebo::msgs::Vector3d* mutable_linear_acceleration();
  void set_allocated_linear_acceleration(::gazebo::msgs::Vector3d* linear_acceleration);
  private:
  const ::gazebo::msgs::Vector3d& _internal_linear_acceleration() const;
  ::gazebo::msgs::Vector3d* _internal_mutable_linear_acceleration();
  public:
  void unsafe_arena_set_allocated_linear_acceleration(
      ::gazebo::msgs::Vector3d* linear_acceleration);
  ::gazebo::msgs::Vector3d* unsafe_arena_release_linear_acceleration();

  // required int64 time_usec = 7;
  bool has_time_usec() const;
  private:
  bool _internal_has_time_usec() const;
  public:
  void clear_time_usec();
  ::PROTOBUF_NAMESPACE_ID::int64 time_usec() const;
  void set_time_usec(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_time_usec() const;
  void _internal_set_time_usec(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // required int64 seq = 8;
  bool has_seq() const;
  private:
  bool _internal_has_seq() const;
  public:
  void clear_seq();
  ::PROTOBUF_NAMESPACE_ID::int64 seq() const;
  void set_seq(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_seq() const;
  void _internal_set_seq(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // @@protoc_insertion_point(class_scope:sensor_msgs.msgs.Imu)
 private:
  class _Internal;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float > orientation_covariance_;
  mutable std::atomic<int> _orientation_covariance_cached_byte_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float > angular_velocity_covariance_;
  mutable std::atomic<int> _angular_velocity_covariance_cached_byte_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float > linear_acceleration_covariance_;
  mutable std::atomic<int> _linear_acceleration_covariance_cached_byte_size_;
  ::gazebo::msgs::Quaternion* orientation_;
  ::gazebo::msgs::Vector3d* angular_velocity_;
  ::gazebo::msgs::Vector3d* linear_acceleration_;
  ::PROTOBUF_NAMESPACE_ID::int64 time_usec_;
  ::PROTOBUF_NAMESPACE_ID::int64 seq_;
  friend struct ::TableStruct_Imu_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Imu

// required .gazebo.msgs.Quaternion orientation = 1;
inline bool Imu::_internal_has_orientation() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || orientation_ != nullptr);
  return value;
}
inline bool Imu::has_orientation() const {
  return _internal_has_orientation();
}
inline const ::gazebo::msgs::Quaternion& Imu::_internal_orientation() const {
  const ::gazebo::msgs::Quaternion* p = orientation_;
  return p != nullptr ? *p : *reinterpret_cast<const ::gazebo::msgs::Quaternion*>(
      &::gazebo::msgs::_Quaternion_default_instance_);
}
inline const ::gazebo::msgs::Quaternion& Imu::orientation() const {
  // @@protoc_insertion_point(field_get:sensor_msgs.msgs.Imu.orientation)
  return _internal_orientation();
}
inline void Imu::unsafe_arena_set_allocated_orientation(
    ::gazebo::msgs::Quaternion* orientation) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(orientation_);
  }
  orientation_ = orientation;
  if (orientation) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:sensor_msgs.msgs.Imu.orientation)
}
inline ::gazebo::msgs::Quaternion* Imu::release_orientation() {
  auto temp = unsafe_arena_release_orientation();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::gazebo::msgs::Quaternion* Imu::unsafe_arena_release_orientation() {
  // @@protoc_insertion_point(field_release:sensor_msgs.msgs.Imu.orientation)
  _has_bits_[0] &= ~0x00000001u;
  ::gazebo::msgs::Quaternion* temp = orientation_;
  orientation_ = nullptr;
  return temp;
}
inline ::gazebo::msgs::Quaternion* Imu::_internal_mutable_orientation() {
  _has_bits_[0] |= 0x00000001u;
  if (orientation_ == nullptr) {
    auto* p = CreateMaybeMessage<::gazebo::msgs::Quaternion>(GetArena());
    orientation_ = p;
  }
  return orientation_;
}
inline ::gazebo::msgs::Quaternion* Imu::mutable_orientation() {
  // @@protoc_insertion_point(field_mutable:sensor_msgs.msgs.Imu.orientation)
  return _internal_mutable_orientation();
}
inline void Imu::set_allocated_orientation(::gazebo::msgs::Quaternion* orientation) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(orientation_);
  }
  if (orientation) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(orientation)->GetArena();
    if (message_arena != submessage_arena) {
      orientation = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, orientation, submessage_arena);
    }
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  orientation_ = orientation;
  // @@protoc_insertion_point(field_set_allocated:sensor_msgs.msgs.Imu.orientation)
}

// repeated float orientation_covariance = 2 [packed = true];
inline int Imu::_internal_orientation_covariance_size() const {
  return orientation_covariance_.size();
}
inline int Imu::orientation_covariance_size() const {
  return _internal_orientation_covariance_size();
}
inline void Imu::clear_orientation_covariance() {
  orientation_covariance_.Clear();
}
inline float Imu::_internal_orientation_covariance(int index) const {
  return orientation_covariance_.Get(index);
}
inline float Imu::orientation_covariance(int index) const {
  // @@protoc_insertion_point(field_get:sensor_msgs.msgs.Imu.orientation_covariance)
  return _internal_orientation_covariance(index);
}
inline void Imu::set_orientation_covariance(int index, float value) {
  orientation_covariance_.Set(index, value);
  // @@protoc_insertion_point(field_set:sensor_msgs.msgs.Imu.orientation_covariance)
}
inline void Imu::_internal_add_orientation_covariance(float value) {
  orientation_covariance_.Add(value);
}
inline void Imu::add_orientation_covariance(float value) {
  _internal_add_orientation_covariance(value);
  // @@protoc_insertion_point(field_add:sensor_msgs.msgs.Imu.orientation_covariance)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
Imu::_internal_orientation_covariance() const {
  return orientation_covariance_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
Imu::orientation_covariance() const {
  // @@protoc_insertion_point(field_list:sensor_msgs.msgs.Imu.orientation_covariance)
  return _internal_orientation_covariance();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
Imu::_internal_mutable_orientation_covariance() {
  return &orientation_covariance_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
Imu::mutable_orientation_covariance() {
  // @@protoc_insertion_point(field_mutable_list:sensor_msgs.msgs.Imu.orientation_covariance)
  return _internal_mutable_orientation_covariance();
}

// required .gazebo.msgs.Vector3d angular_velocity = 3;
inline bool Imu::_internal_has_angular_velocity() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || angular_velocity_ != nullptr);
  return value;
}
inline bool Imu::has_angular_velocity() const {
  return _internal_has_angular_velocity();
}
inline const ::gazebo::msgs::Vector3d& Imu::_internal_angular_velocity() const {
  const ::gazebo::msgs::Vector3d* p = angular_velocity_;
  return p != nullptr ? *p : *reinterpret_cast<const ::gazebo::msgs::Vector3d*>(
      &::gazebo::msgs::_Vector3d_default_instance_);
}
inline const ::gazebo::msgs::Vector3d& Imu::angular_velocity() const {
  // @@protoc_insertion_point(field_get:sensor_msgs.msgs.Imu.angular_velocity)
  return _internal_angular_velocity();
}
inline void Imu::unsafe_arena_set_allocated_angular_velocity(
    ::gazebo::msgs::Vector3d* angular_velocity) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(angular_velocity_);
  }
  angular_velocity_ = angular_velocity;
  if (angular_velocity) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:sensor_msgs.msgs.Imu.angular_velocity)
}
inline ::gazebo::msgs::Vector3d* Imu::release_angular_velocity() {
  auto temp = unsafe_arena_release_angular_velocity();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::gazebo::msgs::Vector3d* Imu::unsafe_arena_release_angular_velocity() {
  // @@protoc_insertion_point(field_release:sensor_msgs.msgs.Imu.angular_velocity)
  _has_bits_[0] &= ~0x00000002u;
  ::gazebo::msgs::Vector3d* temp = angular_velocity_;
  angular_velocity_ = nullptr;
  return temp;
}
inline ::gazebo::msgs::Vector3d* Imu::_internal_mutable_angular_velocity() {
  _has_bits_[0] |= 0x00000002u;
  if (angular_velocity_ == nullptr) {
    auto* p = CreateMaybeMessage<::gazebo::msgs::Vector3d>(GetArena());
    angular_velocity_ = p;
  }
  return angular_velocity_;
}
inline ::gazebo::msgs::Vector3d* Imu::mutable_angular_velocity() {
  // @@protoc_insertion_point(field_mutable:sensor_msgs.msgs.Imu.angular_velocity)
  return _internal_mutable_angular_velocity();
}
inline void Imu::set_allocated_angular_velocity(::gazebo::msgs::Vector3d* angular_velocity) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(angular_velocity_);
  }
  if (angular_velocity) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(angular_velocity)->GetArena();
    if (message_arena != submessage_arena) {
      angular_velocity = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, angular_velocity, submessage_arena);
    }
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  angular_velocity_ = angular_velocity;
  // @@protoc_insertion_point(field_set_allocated:sensor_msgs.msgs.Imu.angular_velocity)
}

// repeated float angular_velocity_covariance = 4 [packed = true];
inline int Imu::_internal_angular_velocity_covariance_size() const {
  return angular_velocity_covariance_.size();
}
inline int Imu::angular_velocity_covariance_size() const {
  return _internal_angular_velocity_covariance_size();
}
inline void Imu::clear_angular_velocity_covariance() {
  angular_velocity_covariance_.Clear();
}
inline float Imu::_internal_angular_velocity_covariance(int index) const {
  return angular_velocity_covariance_.Get(index);
}
inline float Imu::angular_velocity_covariance(int index) const {
  // @@protoc_insertion_point(field_get:sensor_msgs.msgs.Imu.angular_velocity_covariance)
  return _internal_angular_velocity_covariance(index);
}
inline void Imu::set_angular_velocity_covariance(int index, float value) {
  angular_velocity_covariance_.Set(index, value);
  // @@protoc_insertion_point(field_set:sensor_msgs.msgs.Imu.angular_velocity_covariance)
}
inline void Imu::_internal_add_angular_velocity_covariance(float value) {
  angular_velocity_covariance_.Add(value);
}
inline void Imu::add_angular_velocity_covariance(float value) {
  _internal_add_angular_velocity_covariance(value);
  // @@protoc_insertion_point(field_add:sensor_msgs.msgs.Imu.angular_velocity_covariance)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
Imu::_internal_angular_velocity_covariance() const {
  return angular_velocity_covariance_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
Imu::angular_velocity_covariance() const {
  // @@protoc_insertion_point(field_list:sensor_msgs.msgs.Imu.angular_velocity_covariance)
  return _internal_angular_velocity_covariance();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
Imu::_internal_mutable_angular_velocity_covariance() {
  return &angular_velocity_covariance_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
Imu::mutable_angular_velocity_covariance() {
  // @@protoc_insertion_point(field_mutable_list:sensor_msgs.msgs.Imu.angular_velocity_covariance)
  return _internal_mutable_angular_velocity_covariance();
}

// required .gazebo.msgs.Vector3d linear_acceleration = 5;
inline bool Imu::_internal_has_linear_acceleration() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  PROTOBUF_ASSUME(!value || linear_acceleration_ != nullptr);
  return value;
}
inline bool Imu::has_linear_acceleration() const {
  return _internal_has_linear_acceleration();
}
inline const ::gazebo::msgs::Vector3d& Imu::_internal_linear_acceleration() const {
  const ::gazebo::msgs::Vector3d* p = linear_acceleration_;
  return p != nullptr ? *p : *reinterpret_cast<const ::gazebo::msgs::Vector3d*>(
      &::gazebo::msgs::_Vector3d_default_instance_);
}
inline const ::gazebo::msgs::Vector3d& Imu::linear_acceleration() const {
  // @@protoc_insertion_point(field_get:sensor_msgs.msgs.Imu.linear_acceleration)
  return _internal_linear_acceleration();
}
inline void Imu::unsafe_arena_set_allocated_linear_acceleration(
    ::gazebo::msgs::Vector3d* linear_acceleration) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(linear_acceleration_);
  }
  linear_acceleration_ = linear_acceleration;
  if (linear_acceleration) {
    _has_bits_[0] |= 0x00000004u;
  } else {
    _has_bits_[0] &= ~0x00000004u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:sensor_msgs.msgs.Imu.linear_acceleration)
}
inline ::gazebo::msgs::Vector3d* Imu::release_linear_acceleration() {
  auto temp = unsafe_arena_release_linear_acceleration();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::gazebo::msgs::Vector3d* Imu::unsafe_arena_release_linear_acceleration() {
  // @@protoc_insertion_point(field_release:sensor_msgs.msgs.Imu.linear_acceleration)
  _has_bits_[0] &= ~0x00000004u;
  ::gazebo::msgs::Vector3d* temp = linear_acceleration_;
  linear_acceleration_ = nullptr;
  return temp;
}
inline ::gazebo::msgs::Vector3d* Imu::_internal_mutable_linear_acceleration() {
  _has_bits_[0] |= 0x00000004u;
  if (linear_acceleration_ == nullptr) {
    auto* p = CreateMaybeMessage<::gazebo::msgs::Vector3d>(GetArena());
    linear_acceleration_ = p;
  }
  return linear_acceleration_;
}
inline ::gazebo::msgs::Vector3d* Imu::mutable_linear_acceleration() {
  // @@protoc_insertion_point(field_mutable:sensor_msgs.msgs.Imu.linear_acceleration)
  return _internal_mutable_linear_acceleration();
}
inline void Imu::set_allocated_linear_acceleration(::gazebo::msgs::Vector3d* linear_acceleration) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(linear_acceleration_);
  }
  if (linear_acceleration) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(linear_acceleration)->GetArena();
    if (message_arena != submessage_arena) {
      linear_acceleration = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, linear_acceleration, submessage_arena);
    }
    _has_bits_[0] |= 0x00000004u;
  } else {
    _has_bits_[0] &= ~0x00000004u;
  }
  linear_acceleration_ = linear_acceleration;
  // @@protoc_insertion_point(field_set_allocated:sensor_msgs.msgs.Imu.linear_acceleration)
}

// repeated float linear_acceleration_covariance = 6 [packed = true];
inline int Imu::_internal_linear_acceleration_covariance_size() const {
  return linear_acceleration_covariance_.size();
}
inline int Imu::linear_acceleration_covariance_size() const {
  return _internal_linear_acceleration_covariance_size();
}
inline void Imu::clear_linear_acceleration_covariance() {
  linear_acceleration_covariance_.Clear();
}
inline float Imu::_internal_linear_acceleration_covariance(int index) const {
  return linear_acceleration_covariance_.Get(index);
}
inline float Imu::linear_acceleration_covariance(int index) const {
  // @@protoc_insertion_point(field_get:sensor_msgs.msgs.Imu.linear_acceleration_covariance)
  return _internal_linear_acceleration_covariance(index);
}
inline void Imu::set_linear_acceleration_covariance(int index, float value) {
  linear_acceleration_covariance_.Set(index, value);
  // @@protoc_insertion_point(field_set:sensor_msgs.msgs.Imu.linear_acceleration_covariance)
}
inline void Imu::_internal_add_linear_acceleration_covariance(float value) {
  linear_acceleration_covariance_.Add(value);
}
inline void Imu::add_linear_acceleration_covariance(float value) {
  _internal_add_linear_acceleration_covariance(value);
  // @@protoc_insertion_point(field_add:sensor_msgs.msgs.Imu.linear_acceleration_covariance)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
Imu::_internal_linear_acceleration_covariance() const {
  return linear_acceleration_covariance_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
Imu::linear_acceleration_covariance() const {
  // @@protoc_insertion_point(field_list:sensor_msgs.msgs.Imu.linear_acceleration_covariance)
  return _internal_linear_acceleration_covariance();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
Imu::_internal_mutable_linear_acceleration_covariance() {
  return &linear_acceleration_covariance_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
Imu::mutable_linear_acceleration_covariance() {
  // @@protoc_insertion_point(field_mutable_list:sensor_msgs.msgs.Imu.linear_acceleration_covariance)
  return _internal_mutable_linear_acceleration_covariance();
}

// required int64 time_usec = 7;
inline bool Imu::_internal_has_time_usec() const {
  bool value = (_has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool Imu::has_time_usec() const {
  return _internal_has_time_usec();
}
inline void Imu::clear_time_usec() {
  time_usec_ = PROTOBUF_LONGLONG(0);
  _has_bits_[0] &= ~0x00000008u;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 Imu::_internal_time_usec() const {
  return time_usec_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 Imu::time_usec() const {
  // @@protoc_insertion_point(field_get:sensor_msgs.msgs.Imu.time_usec)
  return _internal_time_usec();
}
inline void Imu::_internal_set_time_usec(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _has_bits_[0] |= 0x00000008u;
  time_usec_ = value;
}
inline void Imu::set_time_usec(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_time_usec(value);
  // @@protoc_insertion_point(field_set:sensor_msgs.msgs.Imu.time_usec)
}

// required int64 seq = 8;
inline bool Imu::_internal_has_seq() const {
  bool value = (_has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline bool Imu::has_seq() const {
  return _internal_has_seq();
}
inline void Imu::clear_seq() {
  seq_ = PROTOBUF_LONGLONG(0);
  _has_bits_[0] &= ~0x00000010u;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 Imu::_internal_seq() const {
  return seq_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 Imu::seq() const {
  // @@protoc_insertion_point(field_get:sensor_msgs.msgs.Imu.seq)
  return _internal_seq();
}
inline void Imu::_internal_set_seq(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _has_bits_[0] |= 0x00000010u;
  seq_ = value;
}
inline void Imu::set_seq(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_seq(value);
  // @@protoc_insertion_point(field_set:sensor_msgs.msgs.Imu.seq)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace msgs
}  // namespace sensor_msgs

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_Imu_2eproto
