// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IRLock.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_IRLock_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_IRLock_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_IRLock_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_IRLock_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_IRLock_2eproto;
namespace sensor_msgs {
namespace msgs {
class IRLock;
class IRLockDefaultTypeInternal;
extern IRLockDefaultTypeInternal _IRLock_default_instance_;
}  // namespace msgs
}  // namespace sensor_msgs
PROTOBUF_NAMESPACE_OPEN
template<> ::sensor_msgs::msgs::IRLock* Arena::CreateMaybeMessage<::sensor_msgs::msgs::IRLock>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace sensor_msgs {
namespace msgs {

// ===================================================================

class IRLock PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:sensor_msgs.msgs.IRLock) */ {
 public:
  inline IRLock() : IRLock(nullptr) {};
  virtual ~IRLock();

  IRLock(const IRLock& from);
  IRLock(IRLock&& from) noexcept
    : IRLock() {
    *this = ::std::move(from);
  }

  inline IRLock& operator=(const IRLock& from) {
    CopyFrom(from);
    return *this;
  }
  inline IRLock& operator=(IRLock&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const IRLock& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const IRLock* internal_default_instance() {
    return reinterpret_cast<const IRLock*>(
               &_IRLock_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(IRLock& a, IRLock& b) {
    a.Swap(&b);
  }
  inline void Swap(IRLock* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(IRLock* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline IRLock* New() const final {
    return CreateMaybeMessage<IRLock>(nullptr);
  }

  IRLock* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<IRLock>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const IRLock& from);
  void MergeFrom(const IRLock& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(IRLock* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "sensor_msgs.msgs.IRLock";
  }
  protected:
  explicit IRLock(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_IRLock_2eproto);
    return ::descriptor_table_IRLock_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTimeUsecFieldNumber = 1,
    kSignatureFieldNumber = 2,
    kPosXFieldNumber = 3,
    kPosYFieldNumber = 4,
    kSizeXFieldNumber = 5,
    kQWFieldNumber = 7,
    kQXFieldNumber = 8,
    kQYFieldNumber = 9,
    kQZFieldNumber = 10,
    kAttitudeQWFieldNumber = 11,
    kAttitudeQXFieldNumber = 12,
    kAttitudeQYFieldNumber = 13,
    kAttitudeQZFieldNumber = 14,
    kSizeYFieldNumber = 6,
  };
  // required int64 time_usec = 1;
  bool has_time_usec() const;
  private:
  bool _internal_has_time_usec() const;
  public:
  void clear_time_usec();
  ::PROTOBUF_NAMESPACE_ID::int64 time_usec() const;
  void set_time_usec(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_time_usec() const;
  void _internal_set_time_usec(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // required int32 signature = 2;
  bool has_signature() const;
  private:
  bool _internal_has_signature() const;
  public:
  void clear_signature();
  ::PROTOBUF_NAMESPACE_ID::int32 signature() const;
  void set_signature(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_signature() const;
  void _internal_set_signature(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // required float pos_x = 3;
  bool has_pos_x() const;
  private:
  bool _internal_has_pos_x() const;
  public:
  void clear_pos_x();
  float pos_x() const;
  void set_pos_x(float value);
  private:
  float _internal_pos_x() const;
  void _internal_set_pos_x(float value);
  public:

  // required float pos_y = 4;
  bool has_pos_y() const;
  private:
  bool _internal_has_pos_y() const;
  public:
  void clear_pos_y();
  float pos_y() const;
  void set_pos_y(float value);
  private:
  float _internal_pos_y() const;
  void _internal_set_pos_y(float value);
  public:

  // required float size_x = 5;
  bool has_size_x() const;
  private:
  bool _internal_has_size_x() const;
  public:
  void clear_size_x();
  float size_x() const;
  void set_size_x(float value);
  private:
  float _internal_size_x() const;
  void _internal_set_size_x(float value);
  public:

  // optional double q_w = 7;
  bool has_q_w() const;
  private:
  bool _internal_has_q_w() const;
  public:
  void clear_q_w();
  double q_w() const;
  void set_q_w(double value);
  private:
  double _internal_q_w() const;
  void _internal_set_q_w(double value);
  public:

  // optional double q_x = 8;
  bool has_q_x() const;
  private:
  bool _internal_has_q_x() const;
  public:
  void clear_q_x();
  double q_x() const;
  void set_q_x(double value);
  private:
  double _internal_q_x() const;
  void _internal_set_q_x(double value);
  public:

  // optional double q_y = 9;
  bool has_q_y() const;
  private:
  bool _internal_has_q_y() const;
  public:
  void clear_q_y();
  double q_y() const;
  void set_q_y(double value);
  private:
  double _internal_q_y() const;
  void _internal_set_q_y(double value);
  public:

  // optional double q_z = 10;
  bool has_q_z() const;
  private:
  bool _internal_has_q_z() const;
  public:
  void clear_q_z();
  double q_z() const;
  void set_q_z(double value);
  private:
  double _internal_q_z() const;
  void _internal_set_q_z(double value);
  public:

  // optional double attitude_q_w = 11;
  bool has_attitude_q_w() const;
  private:
  bool _internal_has_attitude_q_w() const;
  public:
  void clear_attitude_q_w();
  double attitude_q_w() const;
  void set_attitude_q_w(double value);
  private:
  double _internal_attitude_q_w() const;
  void _internal_set_attitude_q_w(double value);
  public:

  // optional double attitude_q_x = 12;
  bool has_attitude_q_x() const;
  private:
  bool _internal_has_attitude_q_x() const;
  public:
  void clear_attitude_q_x();
  double attitude_q_x() const;
  void set_attitude_q_x(double value);
  private:
  double _internal_attitude_q_x() const;
  void _internal_set_attitude_q_x(double value);
  public:

  // optional double attitude_q_y = 13;
  bool has_attitude_q_y() const;
  private:
  bool _internal_has_attitude_q_y() const;
  public:
  void clear_attitude_q_y();
  double attitude_q_y() const;
  void set_attitude_q_y(double value);
  private:
  double _internal_attitude_q_y() const;
  void _internal_set_attitude_q_y(double value);
  public:

  // optional double attitude_q_z = 14;
  bool has_attitude_q_z() const;
  private:
  bool _internal_has_attitude_q_z() const;
  public:
  void clear_attitude_q_z();
  double attitude_q_z() const;
  void set_attitude_q_z(double value);
  private:
  double _internal_attitude_q_z() const;
  void _internal_set_attitude_q_z(double value);
  public:

  // required float size_y = 6;
  bool has_size_y() const;
  private:
  bool _internal_has_size_y() const;
  public:
  void clear_size_y();
  float size_y() const;
  void set_size_y(float value);
  private:
  float _internal_size_y() const;
  void _internal_set_size_y(float value);
  public:

  // @@protoc_insertion_point(class_scope:sensor_msgs.msgs.IRLock)
 private:
  class _Internal;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::int64 time_usec_;
  ::PROTOBUF_NAMESPACE_ID::int32 signature_;
  float pos_x_;
  float pos_y_;
  float size_x_;
  double q_w_;
  double q_x_;
  double q_y_;
  double q_z_;
  double attitude_q_w_;
  double attitude_q_x_;
  double attitude_q_y_;
  double attitude_q_z_;
  float size_y_;
  friend struct ::TableStruct_IRLock_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// IRLock

// required int64 time_usec = 1;
inline bool IRLock::_internal_has_time_usec() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool IRLock::has_time_usec() const {
  return _internal_has_time_usec();
}
inline void IRLock::clear_time_usec() {
  time_usec_ = PROTOBUF_LONGLONG(0);
  _has_bits_[0] &= ~0x00000001u;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 IRLock::_internal_time_usec() const {
  return time_usec_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 IRLock::time_usec() const {
  // @@protoc_insertion_point(field_get:sensor_msgs.msgs.IRLock.time_usec)
  return _internal_time_usec();
}
inline void IRLock::_internal_set_time_usec(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _has_bits_[0] |= 0x00000001u;
  time_usec_ = value;
}
inline void IRLock::set_time_usec(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_time_usec(value);
  // @@protoc_insertion_point(field_set:sensor_msgs.msgs.IRLock.time_usec)
}

// required int32 signature = 2;
inline bool IRLock::_internal_has_signature() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool IRLock::has_signature() const {
  return _internal_has_signature();
}
inline void IRLock::clear_signature() {
  signature_ = 0;
  _has_bits_[0] &= ~0x00000002u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 IRLock::_internal_signature() const {
  return signature_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 IRLock::signature() const {
  // @@protoc_insertion_point(field_get:sensor_msgs.msgs.IRLock.signature)
  return _internal_signature();
}
inline void IRLock::_internal_set_signature(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00000002u;
  signature_ = value;
}
inline void IRLock::set_signature(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_signature(value);
  // @@protoc_insertion_point(field_set:sensor_msgs.msgs.IRLock.signature)
}

// required float pos_x = 3;
inline bool IRLock::_internal_has_pos_x() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool IRLock::has_pos_x() const {
  return _internal_has_pos_x();
}
inline void IRLock::clear_pos_x() {
  pos_x_ = 0;
  _has_bits_[0] &= ~0x00000004u;
}
inline float IRLock::_internal_pos_x() const {
  return pos_x_;
}
inline float IRLock::pos_x() const {
  // @@protoc_insertion_point(field_get:sensor_msgs.msgs.IRLock.pos_x)
  return _internal_pos_x();
}
inline void IRLock::_internal_set_pos_x(float value) {
  _has_bits_[0] |= 0x00000004u;
  pos_x_ = value;
}
inline void IRLock::set_pos_x(float value) {
  _internal_set_pos_x(value);
  // @@protoc_insertion_point(field_set:sensor_msgs.msgs.IRLock.pos_x)
}

// required float pos_y = 4;
inline bool IRLock::_internal_has_pos_y() const {
  bool value = (_has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool IRLock::has_pos_y() const {
  return _internal_has_pos_y();
}
inline void IRLock::clear_pos_y() {
  pos_y_ = 0;
  _has_bits_[0] &= ~0x00000008u;
}
inline float IRLock::_internal_pos_y() const {
  return pos_y_;
}
inline float IRLock::pos_y() const {
  // @@protoc_insertion_point(field_get:sensor_msgs.msgs.IRLock.pos_y)
  return _internal_pos_y();
}
inline void IRLock::_internal_set_pos_y(float value) {
  _has_bits_[0] |= 0x00000008u;
  pos_y_ = value;
}
inline void IRLock::set_pos_y(float value) {
  _internal_set_pos_y(value);
  // @@protoc_insertion_point(field_set:sensor_msgs.msgs.IRLock.pos_y)
}

// required float size_x = 5;
inline bool IRLock::_internal_has_size_x() const {
  bool value = (_has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline bool IRLock::has_size_x() const {
  return _internal_has_size_x();
}
inline void IRLock::clear_size_x() {
  size_x_ = 0;
  _has_bits_[0] &= ~0x00000010u;
}
inline float IRLock::_internal_size_x() const {
  return size_x_;
}
inline float IRLock::size_x() const {
  // @@protoc_insertion_point(field_get:sensor_msgs.msgs.IRLock.size_x)
  return _internal_size_x();
}
inline void IRLock::_internal_set_size_x(float value) {
  _has_bits_[0] |= 0x00000010u;
  size_x_ = value;
}
inline void IRLock::set_size_x(float value) {
  _internal_set_size_x(value);
  // @@protoc_insertion_point(field_set:sensor_msgs.msgs.IRLock.size_x)
}

// required float size_y = 6;
inline bool IRLock::_internal_has_size_y() const {
  bool value = (_has_bits_[0] & 0x00002000u) != 0;
  return value;
}
inline bool IRLock::has_size_y() const {
  return _internal_has_size_y();
}
inline void IRLock::clear_size_y() {
  size_y_ = 0;
  _has_bits_[0] &= ~0x00002000u;
}
inline float IRLock::_internal_size_y() const {
  return size_y_;
}
inline float IRLock::size_y() const {
  // @@protoc_insertion_point(field_get:sensor_msgs.msgs.IRLock.size_y)
  return _internal_size_y();
}
inline void IRLock::_internal_set_size_y(float value) {
  _has_bits_[0] |= 0x00002000u;
  size_y_ = value;
}
inline void IRLock::set_size_y(float value) {
  _internal_set_size_y(value);
  // @@protoc_insertion_point(field_set:sensor_msgs.msgs.IRLock.size_y)
}

// optional double q_w = 7;
inline bool IRLock::_internal_has_q_w() const {
  bool value = (_has_bits_[0] & 0x00000020u) != 0;
  return value;
}
inline bool IRLock::has_q_w() const {
  return _internal_has_q_w();
}
inline void IRLock::clear_q_w() {
  q_w_ = 0;
  _has_bits_[0] &= ~0x00000020u;
}
inline double IRLock::_internal_q_w() const {
  return q_w_;
}
inline double IRLock::q_w() const {
  // @@protoc_insertion_point(field_get:sensor_msgs.msgs.IRLock.q_w)
  return _internal_q_w();
}
inline void IRLock::_internal_set_q_w(double value) {
  _has_bits_[0] |= 0x00000020u;
  q_w_ = value;
}
inline void IRLock::set_q_w(double value) {
  _internal_set_q_w(value);
  // @@protoc_insertion_point(field_set:sensor_msgs.msgs.IRLock.q_w)
}

// optional double q_x = 8;
inline bool IRLock::_internal_has_q_x() const {
  bool value = (_has_bits_[0] & 0x00000040u) != 0;
  return value;
}
inline bool IRLock::has_q_x() const {
  return _internal_has_q_x();
}
inline void IRLock::clear_q_x() {
  q_x_ = 0;
  _has_bits_[0] &= ~0x00000040u;
}
inline double IRLock::_internal_q_x() const {
  return q_x_;
}
inline double IRLock::q_x() const {
  // @@protoc_insertion_point(field_get:sensor_msgs.msgs.IRLock.q_x)
  return _internal_q_x();
}
inline void IRLock::_internal_set_q_x(double value) {
  _has_bits_[0] |= 0x00000040u;
  q_x_ = value;
}
inline void IRLock::set_q_x(double value) {
  _internal_set_q_x(value);
  // @@protoc_insertion_point(field_set:sensor_msgs.msgs.IRLock.q_x)
}

// optional double q_y = 9;
inline bool IRLock::_internal_has_q_y() const {
  bool value = (_has_bits_[0] & 0x00000080u) != 0;
  return value;
}
inline bool IRLock::has_q_y() const {
  return _internal_has_q_y();
}
inline void IRLock::clear_q_y() {
  q_y_ = 0;
  _has_bits_[0] &= ~0x00000080u;
}
inline double IRLock::_internal_q_y() const {
  return q_y_;
}
inline double IRLock::q_y() const {
  // @@protoc_insertion_point(field_get:sensor_msgs.msgs.IRLock.q_y)
  return _internal_q_y();
}
inline void IRLock::_internal_set_q_y(double value) {
  _has_bits_[0] |= 0x00000080u;
  q_y_ = value;
}
inline void IRLock::set_q_y(double value) {
  _internal_set_q_y(value);
  // @@protoc_insertion_point(field_set:sensor_msgs.msgs.IRLock.q_y)
}

// optional double q_z = 10;
inline bool IRLock::_internal_has_q_z() const {
  bool value = (_has_bits_[0] & 0x00000100u) != 0;
  return value;
}
inline bool IRLock::has_q_z() const {
  return _internal_has_q_z();
}
inline void IRLock::clear_q_z() {
  q_z_ = 0;
  _has_bits_[0] &= ~0x00000100u;
}
inline double IRLock::_internal_q_z() const {
  return q_z_;
}
inline double IRLock::q_z() const {
  // @@protoc_insertion_point(field_get:sensor_msgs.msgs.IRLock.q_z)
  return _internal_q_z();
}
inline void IRLock::_internal_set_q_z(double value) {
  _has_bits_[0] |= 0x00000100u;
  q_z_ = value;
}
inline void IRLock::set_q_z(double value) {
  _internal_set_q_z(value);
  // @@protoc_insertion_point(field_set:sensor_msgs.msgs.IRLock.q_z)
}

// optional double attitude_q_w = 11;
inline bool IRLock::_internal_has_attitude_q_w() const {
  bool value = (_has_bits_[0] & 0x00000200u) != 0;
  return value;
}
inline bool IRLock::has_attitude_q_w() const {
  return _internal_has_attitude_q_w();
}
inline void IRLock::clear_attitude_q_w() {
  attitude_q_w_ = 0;
  _has_bits_[0] &= ~0x00000200u;
}
inline double IRLock::_internal_attitude_q_w() const {
  return attitude_q_w_;
}
inline double IRLock::attitude_q_w() const {
  // @@protoc_insertion_point(field_get:sensor_msgs.msgs.IRLock.attitude_q_w)
  return _internal_attitude_q_w();
}
inline void IRLock::_internal_set_attitude_q_w(double value) {
  _has_bits_[0] |= 0x00000200u;
  attitude_q_w_ = value;
}
inline void IRLock::set_attitude_q_w(double value) {
  _internal_set_attitude_q_w(value);
  // @@protoc_insertion_point(field_set:sensor_msgs.msgs.IRLock.attitude_q_w)
}

// optional double attitude_q_x = 12;
inline bool IRLock::_internal_has_attitude_q_x() const {
  bool value = (_has_bits_[0] & 0x00000400u) != 0;
  return value;
}
inline bool IRLock::has_attitude_q_x() const {
  return _internal_has_attitude_q_x();
}
inline void IRLock::clear_attitude_q_x() {
  attitude_q_x_ = 0;
  _has_bits_[0] &= ~0x00000400u;
}
inline double IRLock::_internal_attitude_q_x() const {
  return attitude_q_x_;
}
inline double IRLock::attitude_q_x() const {
  // @@protoc_insertion_point(field_get:sensor_msgs.msgs.IRLock.attitude_q_x)
  return _internal_attitude_q_x();
}
inline void IRLock::_internal_set_attitude_q_x(double value) {
  _has_bits_[0] |= 0x00000400u;
  attitude_q_x_ = value;
}
inline void IRLock::set_attitude_q_x(double value) {
  _internal_set_attitude_q_x(value);
  // @@protoc_insertion_point(field_set:sensor_msgs.msgs.IRLock.attitude_q_x)
}

// optional double attitude_q_y = 13;
inline bool IRLock::_internal_has_attitude_q_y() const {
  bool value = (_has_bits_[0] & 0x00000800u) != 0;
  return value;
}
inline bool IRLock::has_attitude_q_y() const {
  return _internal_has_attitude_q_y();
}
inline void IRLock::clear_attitude_q_y() {
  attitude_q_y_ = 0;
  _has_bits_[0] &= ~0x00000800u;
}
inline double IRLock::_internal_attitude_q_y() const {
  return attitude_q_y_;
}
inline double IRLock::attitude_q_y() const {
  // @@protoc_insertion_point(field_get:sensor_msgs.msgs.IRLock.attitude_q_y)
  return _internal_attitude_q_y();
}
inline void IRLock::_internal_set_attitude_q_y(double value) {
  _has_bits_[0] |= 0x00000800u;
  attitude_q_y_ = value;
}
inline void IRLock::set_attitude_q_y(double value) {
  _internal_set_attitude_q_y(value);
  // @@protoc_insertion_point(field_set:sensor_msgs.msgs.IRLock.attitude_q_y)
}

// optional double attitude_q_z = 14;
inline bool IRLock::_internal_has_attitude_q_z() const {
  bool value = (_has_bits_[0] & 0x00001000u) != 0;
  return value;
}
inline bool IRLock::has_attitude_q_z() const {
  return _internal_has_attitude_q_z();
}
inline void IRLock::clear_attitude_q_z() {
  attitude_q_z_ = 0;
  _has_bits_[0] &= ~0x00001000u;
}
inline double IRLock::_internal_attitude_q_z() const {
  return attitude_q_z_;
}
inline double IRLock::attitude_q_z() const {
  // @@protoc_insertion_point(field_get:sensor_msgs.msgs.IRLock.attitude_q_z)
  return _internal_attitude_q_z();
}
inline void IRLock::_internal_set_attitude_q_z(double value) {
  _has_bits_[0] |= 0x00001000u;
  attitude_q_z_ = value;
}
inline void IRLock::set_attitude_q_z(double value) {
  _internal_set_attitude_q_z(value);
  // @@protoc_insertion_point(field_set:sensor_msgs.msgs.IRLock.attitude_q_z)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace msgs
}  // namespace sensor_msgs

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_IRLock_2eproto
