// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MotorSpeed.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_MotorSpeed_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_MotorSpeed_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_MotorSpeed_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_MotorSpeed_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_MotorSpeed_2eproto;
namespace mav_msgs {
namespace msgs {
class MotorSpeed;
class MotorSpeedDefaultTypeInternal;
extern MotorSpeedDefaultTypeInternal _MotorSpeed_default_instance_;
}  // namespace msgs
}  // namespace mav_msgs
PROTOBUF_NAMESPACE_OPEN
template<> ::mav_msgs::msgs::MotorSpeed* Arena::CreateMaybeMessage<::mav_msgs::msgs::MotorSpeed>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace mav_msgs {
namespace msgs {

// ===================================================================

class MotorSpeed PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:mav_msgs.msgs.MotorSpeed) */ {
 public:
  inline MotorSpeed() : MotorSpeed(nullptr) {};
  virtual ~MotorSpeed();

  MotorSpeed(const MotorSpeed& from);
  MotorSpeed(MotorSpeed&& from) noexcept
    : MotorSpeed() {
    *this = ::std::move(from);
  }

  inline MotorSpeed& operator=(const MotorSpeed& from) {
    CopyFrom(from);
    return *this;
  }
  inline MotorSpeed& operator=(MotorSpeed&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const MotorSpeed& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const MotorSpeed* internal_default_instance() {
    return reinterpret_cast<const MotorSpeed*>(
               &_MotorSpeed_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(MotorSpeed& a, MotorSpeed& b) {
    a.Swap(&b);
  }
  inline void Swap(MotorSpeed* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MotorSpeed* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline MotorSpeed* New() const final {
    return CreateMaybeMessage<MotorSpeed>(nullptr);
  }

  MotorSpeed* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<MotorSpeed>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const MotorSpeed& from);
  void MergeFrom(const MotorSpeed& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MotorSpeed* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "mav_msgs.msgs.MotorSpeed";
  }
  protected:
  explicit MotorSpeed(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_MotorSpeed_2eproto);
    return ::descriptor_table_MotorSpeed_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMotorSpeedFieldNumber = 1,
  };
  // repeated float motor_speed = 1 [packed = true];
  int motor_speed_size() const;
  private:
  int _internal_motor_speed_size() const;
  public:
  void clear_motor_speed();
  private:
  float _internal_motor_speed(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      _internal_motor_speed() const;
  void _internal_add_motor_speed(float value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      _internal_mutable_motor_speed();
  public:
  float motor_speed(int index) const;
  void set_motor_speed(int index, float value);
  void add_motor_speed(float value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      motor_speed() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      mutable_motor_speed();

  // @@protoc_insertion_point(class_scope:mav_msgs.msgs.MotorSpeed)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float > motor_speed_;
  mutable std::atomic<int> _motor_speed_cached_byte_size_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_MotorSpeed_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// MotorSpeed

// repeated float motor_speed = 1 [packed = true];
inline int MotorSpeed::_internal_motor_speed_size() const {
  return motor_speed_.size();
}
inline int MotorSpeed::motor_speed_size() const {
  return _internal_motor_speed_size();
}
inline void MotorSpeed::clear_motor_speed() {
  motor_speed_.Clear();
}
inline float MotorSpeed::_internal_motor_speed(int index) const {
  return motor_speed_.Get(index);
}
inline float MotorSpeed::motor_speed(int index) const {
  // @@protoc_insertion_point(field_get:mav_msgs.msgs.MotorSpeed.motor_speed)
  return _internal_motor_speed(index);
}
inline void MotorSpeed::set_motor_speed(int index, float value) {
  motor_speed_.Set(index, value);
  // @@protoc_insertion_point(field_set:mav_msgs.msgs.MotorSpeed.motor_speed)
}
inline void MotorSpeed::_internal_add_motor_speed(float value) {
  motor_speed_.Add(value);
}
inline void MotorSpeed::add_motor_speed(float value) {
  _internal_add_motor_speed(value);
  // @@protoc_insertion_point(field_add:mav_msgs.msgs.MotorSpeed.motor_speed)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
MotorSpeed::_internal_motor_speed() const {
  return motor_speed_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
MotorSpeed::motor_speed() const {
  // @@protoc_insertion_point(field_list:mav_msgs.msgs.MotorSpeed.motor_speed)
  return _internal_motor_speed();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
MotorSpeed::_internal_mutable_motor_speed() {
  return &motor_speed_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
MotorSpeed::mutable_motor_speed() {
  // @@protoc_insertion_point(field_mutable_list:mav_msgs.msgs.MotorSpeed.motor_speed)
  return _internal_mutable_motor_speed();
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace msgs
}  // namespace mav_msgs

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_MotorSpeed_2eproto
