// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TargetRelative.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_TargetRelative_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_TargetRelative_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_TargetRelative_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_TargetRelative_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_TargetRelative_2eproto;
namespace sensor_msgs {
namespace msgs {
class TargetRelative;
class TargetRelativeDefaultTypeInternal;
extern TargetRelativeDefaultTypeInternal _TargetRelative_default_instance_;
}  // namespace msgs
}  // namespace sensor_msgs
PROTOBUF_NAMESPACE_OPEN
template<> ::sensor_msgs::msgs::TargetRelative* Arena::CreateMaybeMessage<::sensor_msgs::msgs::TargetRelative>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace sensor_msgs {
namespace msgs {

// ===================================================================

class TargetRelative PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:sensor_msgs.msgs.TargetRelative) */ {
 public:
  inline TargetRelative() : TargetRelative(nullptr) {};
  virtual ~TargetRelative();

  TargetRelative(const TargetRelative& from);
  TargetRelative(TargetRelative&& from) noexcept
    : TargetRelative() {
    *this = ::std::move(from);
  }

  inline TargetRelative& operator=(const TargetRelative& from) {
    CopyFrom(from);
    return *this;
  }
  inline TargetRelative& operator=(TargetRelative&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const TargetRelative& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const TargetRelative* internal_default_instance() {
    return reinterpret_cast<const TargetRelative*>(
               &_TargetRelative_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(TargetRelative& a, TargetRelative& b) {
    a.Swap(&b);
  }
  inline void Swap(TargetRelative* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TargetRelative* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline TargetRelative* New() const final {
    return CreateMaybeMessage<TargetRelative>(nullptr);
  }

  TargetRelative* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<TargetRelative>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const TargetRelative& from);
  void MergeFrom(const TargetRelative& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TargetRelative* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "sensor_msgs.msgs.TargetRelative";
  }
  protected:
  explicit TargetRelative(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_TargetRelative_2eproto);
    return ::descriptor_table_TargetRelative_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTimeUsecFieldNumber = 1,
    kPosXFieldNumber = 2,
    kPosYFieldNumber = 3,
    kAttitudeQWFieldNumber = 5,
    kAttitudeQXFieldNumber = 6,
    kAttitudeQYFieldNumber = 7,
    kAttitudeQZFieldNumber = 8,
    kPosZFieldNumber = 4,
    kYawStdFieldNumber = 13,
    kOrientationQWFieldNumber = 9,
    kOrientationQXFieldNumber = 10,
    kOrientationQYFieldNumber = 11,
    kOrientationQZFieldNumber = 12,
    kStdXFieldNumber = 14,
    kStdYFieldNumber = 15,
    kStdZFieldNumber = 16,
  };
  // required int64 time_usec = 1;
  bool has_time_usec() const;
  private:
  bool _internal_has_time_usec() const;
  public:
  void clear_time_usec();
  ::PROTOBUF_NAMESPACE_ID::int64 time_usec() const;
  void set_time_usec(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_time_usec() const;
  void _internal_set_time_usec(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // required float pos_x = 2;
  bool has_pos_x() const;
  private:
  bool _internal_has_pos_x() const;
  public:
  void clear_pos_x();
  float pos_x() const;
  void set_pos_x(float value);
  private:
  float _internal_pos_x() const;
  void _internal_set_pos_x(float value);
  public:

  // required float pos_y = 3;
  bool has_pos_y() const;
  private:
  bool _internal_has_pos_y() const;
  public:
  void clear_pos_y();
  float pos_y() const;
  void set_pos_y(float value);
  private:
  float _internal_pos_y() const;
  void _internal_set_pos_y(float value);
  public:

  // optional double attitude_q_w = 5;
  bool has_attitude_q_w() const;
  private:
  bool _internal_has_attitude_q_w() const;
  public:
  void clear_attitude_q_w();
  double attitude_q_w() const;
  void set_attitude_q_w(double value);
  private:
  double _internal_attitude_q_w() const;
  void _internal_set_attitude_q_w(double value);
  public:

  // optional double attitude_q_x = 6;
  bool has_attitude_q_x() const;
  private:
  bool _internal_has_attitude_q_x() const;
  public:
  void clear_attitude_q_x();
  double attitude_q_x() const;
  void set_attitude_q_x(double value);
  private:
  double _internal_attitude_q_x() const;
  void _internal_set_attitude_q_x(double value);
  public:

  // optional double attitude_q_y = 7;
  bool has_attitude_q_y() const;
  private:
  bool _internal_has_attitude_q_y() const;
  public:
  void clear_attitude_q_y();
  double attitude_q_y() const;
  void set_attitude_q_y(double value);
  private:
  double _internal_attitude_q_y() const;
  void _internal_set_attitude_q_y(double value);
  public:

  // optional double attitude_q_z = 8;
  bool has_attitude_q_z() const;
  private:
  bool _internal_has_attitude_q_z() const;
  public:
  void clear_attitude_q_z();
  double attitude_q_z() const;
  void set_attitude_q_z(double value);
  private:
  double _internal_attitude_q_z() const;
  void _internal_set_attitude_q_z(double value);
  public:

  // required float pos_z = 4;
  bool has_pos_z() const;
  private:
  bool _internal_has_pos_z() const;
  public:
  void clear_pos_z();
  float pos_z() const;
  void set_pos_z(float value);
  private:
  float _internal_pos_z() const;
  void _internal_set_pos_z(float value);
  public:

  // optional float yaw_std = 13;
  bool has_yaw_std() const;
  private:
  bool _internal_has_yaw_std() const;
  public:
  void clear_yaw_std();
  float yaw_std() const;
  void set_yaw_std(float value);
  private:
  float _internal_yaw_std() const;
  void _internal_set_yaw_std(float value);
  public:

  // optional double orientation_q_w = 9;
  bool has_orientation_q_w() const;
  private:
  bool _internal_has_orientation_q_w() const;
  public:
  void clear_orientation_q_w();
  double orientation_q_w() const;
  void set_orientation_q_w(double value);
  private:
  double _internal_orientation_q_w() const;
  void _internal_set_orientation_q_w(double value);
  public:

  // optional double orientation_q_x = 10;
  bool has_orientation_q_x() const;
  private:
  bool _internal_has_orientation_q_x() const;
  public:
  void clear_orientation_q_x();
  double orientation_q_x() const;
  void set_orientation_q_x(double value);
  private:
  double _internal_orientation_q_x() const;
  void _internal_set_orientation_q_x(double value);
  public:

  // optional double orientation_q_y = 11;
  bool has_orientation_q_y() const;
  private:
  bool _internal_has_orientation_q_y() const;
  public:
  void clear_orientation_q_y();
  double orientation_q_y() const;
  void set_orientation_q_y(double value);
  private:
  double _internal_orientation_q_y() const;
  void _internal_set_orientation_q_y(double value);
  public:

  // optional double orientation_q_z = 12;
  bool has_orientation_q_z() const;
  private:
  bool _internal_has_orientation_q_z() const;
  public:
  void clear_orientation_q_z();
  double orientation_q_z() const;
  void set_orientation_q_z(double value);
  private:
  double _internal_orientation_q_z() const;
  void _internal_set_orientation_q_z(double value);
  public:

  // optional float std_x = 14;
  bool has_std_x() const;
  private:
  bool _internal_has_std_x() const;
  public:
  void clear_std_x();
  float std_x() const;
  void set_std_x(float value);
  private:
  float _internal_std_x() const;
  void _internal_set_std_x(float value);
  public:

  // optional float std_y = 15;
  bool has_std_y() const;
  private:
  bool _internal_has_std_y() const;
  public:
  void clear_std_y();
  float std_y() const;
  void set_std_y(float value);
  private:
  float _internal_std_y() const;
  void _internal_set_std_y(float value);
  public:

  // optional float std_z = 16;
  bool has_std_z() const;
  private:
  bool _internal_has_std_z() const;
  public:
  void clear_std_z();
  float std_z() const;
  void set_std_z(float value);
  private:
  float _internal_std_z() const;
  void _internal_set_std_z(float value);
  public:

  // @@protoc_insertion_point(class_scope:sensor_msgs.msgs.TargetRelative)
 private:
  class _Internal;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::int64 time_usec_;
  float pos_x_;
  float pos_y_;
  double attitude_q_w_;
  double attitude_q_x_;
  double attitude_q_y_;
  double attitude_q_z_;
  float pos_z_;
  float yaw_std_;
  double orientation_q_w_;
  double orientation_q_x_;
  double orientation_q_y_;
  double orientation_q_z_;
  float std_x_;
  float std_y_;
  float std_z_;
  friend struct ::TableStruct_TargetRelative_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// TargetRelative

// required int64 time_usec = 1;
inline bool TargetRelative::_internal_has_time_usec() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool TargetRelative::has_time_usec() const {
  return _internal_has_time_usec();
}
inline void TargetRelative::clear_time_usec() {
  time_usec_ = PROTOBUF_LONGLONG(0);
  _has_bits_[0] &= ~0x00000001u;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 TargetRelative::_internal_time_usec() const {
  return time_usec_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 TargetRelative::time_usec() const {
  // @@protoc_insertion_point(field_get:sensor_msgs.msgs.TargetRelative.time_usec)
  return _internal_time_usec();
}
inline void TargetRelative::_internal_set_time_usec(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _has_bits_[0] |= 0x00000001u;
  time_usec_ = value;
}
inline void TargetRelative::set_time_usec(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_time_usec(value);
  // @@protoc_insertion_point(field_set:sensor_msgs.msgs.TargetRelative.time_usec)
}

// required float pos_x = 2;
inline bool TargetRelative::_internal_has_pos_x() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool TargetRelative::has_pos_x() const {
  return _internal_has_pos_x();
}
inline void TargetRelative::clear_pos_x() {
  pos_x_ = 0;
  _has_bits_[0] &= ~0x00000002u;
}
inline float TargetRelative::_internal_pos_x() const {
  return pos_x_;
}
inline float TargetRelative::pos_x() const {
  // @@protoc_insertion_point(field_get:sensor_msgs.msgs.TargetRelative.pos_x)
  return _internal_pos_x();
}
inline void TargetRelative::_internal_set_pos_x(float value) {
  _has_bits_[0] |= 0x00000002u;
  pos_x_ = value;
}
inline void TargetRelative::set_pos_x(float value) {
  _internal_set_pos_x(value);
  // @@protoc_insertion_point(field_set:sensor_msgs.msgs.TargetRelative.pos_x)
}

// required float pos_y = 3;
inline bool TargetRelative::_internal_has_pos_y() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool TargetRelative::has_pos_y() const {
  return _internal_has_pos_y();
}
inline void TargetRelative::clear_pos_y() {
  pos_y_ = 0;
  _has_bits_[0] &= ~0x00000004u;
}
inline float TargetRelative::_internal_pos_y() const {
  return pos_y_;
}
inline float TargetRelative::pos_y() const {
  // @@protoc_insertion_point(field_get:sensor_msgs.msgs.TargetRelative.pos_y)
  return _internal_pos_y();
}
inline void TargetRelative::_internal_set_pos_y(float value) {
  _has_bits_[0] |= 0x00000004u;
  pos_y_ = value;
}
inline void TargetRelative::set_pos_y(float value) {
  _internal_set_pos_y(value);
  // @@protoc_insertion_point(field_set:sensor_msgs.msgs.TargetRelative.pos_y)
}

// required float pos_z = 4;
inline bool TargetRelative::_internal_has_pos_z() const {
  bool value = (_has_bits_[0] & 0x00000080u) != 0;
  return value;
}
inline bool TargetRelative::has_pos_z() const {
  return _internal_has_pos_z();
}
inline void TargetRelative::clear_pos_z() {
  pos_z_ = 0;
  _has_bits_[0] &= ~0x00000080u;
}
inline float TargetRelative::_internal_pos_z() const {
  return pos_z_;
}
inline float TargetRelative::pos_z() const {
  // @@protoc_insertion_point(field_get:sensor_msgs.msgs.TargetRelative.pos_z)
  return _internal_pos_z();
}
inline void TargetRelative::_internal_set_pos_z(float value) {
  _has_bits_[0] |= 0x00000080u;
  pos_z_ = value;
}
inline void TargetRelative::set_pos_z(float value) {
  _internal_set_pos_z(value);
  // @@protoc_insertion_point(field_set:sensor_msgs.msgs.TargetRelative.pos_z)
}

// optional double attitude_q_w = 5;
inline bool TargetRelative::_internal_has_attitude_q_w() const {
  bool value = (_has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool TargetRelative::has_attitude_q_w() const {
  return _internal_has_attitude_q_w();
}
inline void TargetRelative::clear_attitude_q_w() {
  attitude_q_w_ = 0;
  _has_bits_[0] &= ~0x00000008u;
}
inline double TargetRelative::_internal_attitude_q_w() const {
  return attitude_q_w_;
}
inline double TargetRelative::attitude_q_w() const {
  // @@protoc_insertion_point(field_get:sensor_msgs.msgs.TargetRelative.attitude_q_w)
  return _internal_attitude_q_w();
}
inline void TargetRelative::_internal_set_attitude_q_w(double value) {
  _has_bits_[0] |= 0x00000008u;
  attitude_q_w_ = value;
}
inline void TargetRelative::set_attitude_q_w(double value) {
  _internal_set_attitude_q_w(value);
  // @@protoc_insertion_point(field_set:sensor_msgs.msgs.TargetRelative.attitude_q_w)
}

// optional double attitude_q_x = 6;
inline bool TargetRelative::_internal_has_attitude_q_x() const {
  bool value = (_has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline bool TargetRelative::has_attitude_q_x() const {
  return _internal_has_attitude_q_x();
}
inline void TargetRelative::clear_attitude_q_x() {
  attitude_q_x_ = 0;
  _has_bits_[0] &= ~0x00000010u;
}
inline double TargetRelative::_internal_attitude_q_x() const {
  return attitude_q_x_;
}
inline double TargetRelative::attitude_q_x() const {
  // @@protoc_insertion_point(field_get:sensor_msgs.msgs.TargetRelative.attitude_q_x)
  return _internal_attitude_q_x();
}
inline void TargetRelative::_internal_set_attitude_q_x(double value) {
  _has_bits_[0] |= 0x00000010u;
  attitude_q_x_ = value;
}
inline void TargetRelative::set_attitude_q_x(double value) {
  _internal_set_attitude_q_x(value);
  // @@protoc_insertion_point(field_set:sensor_msgs.msgs.TargetRelative.attitude_q_x)
}

// optional double attitude_q_y = 7;
inline bool TargetRelative::_internal_has_attitude_q_y() const {
  bool value = (_has_bits_[0] & 0x00000020u) != 0;
  return value;
}
inline bool TargetRelative::has_attitude_q_y() const {
  return _internal_has_attitude_q_y();
}
inline void TargetRelative::clear_attitude_q_y() {
  attitude_q_y_ = 0;
  _has_bits_[0] &= ~0x00000020u;
}
inline double TargetRelative::_internal_attitude_q_y() const {
  return attitude_q_y_;
}
inline double TargetRelative::attitude_q_y() const {
  // @@protoc_insertion_point(field_get:sensor_msgs.msgs.TargetRelative.attitude_q_y)
  return _internal_attitude_q_y();
}
inline void TargetRelative::_internal_set_attitude_q_y(double value) {
  _has_bits_[0] |= 0x00000020u;
  attitude_q_y_ = value;
}
inline void TargetRelative::set_attitude_q_y(double value) {
  _internal_set_attitude_q_y(value);
  // @@protoc_insertion_point(field_set:sensor_msgs.msgs.TargetRelative.attitude_q_y)
}

// optional double attitude_q_z = 8;
inline bool TargetRelative::_internal_has_attitude_q_z() const {
  bool value = (_has_bits_[0] & 0x00000040u) != 0;
  return value;
}
inline bool TargetRelative::has_attitude_q_z() const {
  return _internal_has_attitude_q_z();
}
inline void TargetRelative::clear_attitude_q_z() {
  attitude_q_z_ = 0;
  _has_bits_[0] &= ~0x00000040u;
}
inline double TargetRelative::_internal_attitude_q_z() const {
  return attitude_q_z_;
}
inline double TargetRelative::attitude_q_z() const {
  // @@protoc_insertion_point(field_get:sensor_msgs.msgs.TargetRelative.attitude_q_z)
  return _internal_attitude_q_z();
}
inline void TargetRelative::_internal_set_attitude_q_z(double value) {
  _has_bits_[0] |= 0x00000040u;
  attitude_q_z_ = value;
}
inline void TargetRelative::set_attitude_q_z(double value) {
  _internal_set_attitude_q_z(value);
  // @@protoc_insertion_point(field_set:sensor_msgs.msgs.TargetRelative.attitude_q_z)
}

// optional double orientation_q_w = 9;
inline bool TargetRelative::_internal_has_orientation_q_w() const {
  bool value = (_has_bits_[0] & 0x00000200u) != 0;
  return value;
}
inline bool TargetRelative::has_orientation_q_w() const {
  return _internal_has_orientation_q_w();
}
inline void TargetRelative::clear_orientation_q_w() {
  orientation_q_w_ = 0;
  _has_bits_[0] &= ~0x00000200u;
}
inline double TargetRelative::_internal_orientation_q_w() const {
  return orientation_q_w_;
}
inline double TargetRelative::orientation_q_w() const {
  // @@protoc_insertion_point(field_get:sensor_msgs.msgs.TargetRelative.orientation_q_w)
  return _internal_orientation_q_w();
}
inline void TargetRelative::_internal_set_orientation_q_w(double value) {
  _has_bits_[0] |= 0x00000200u;
  orientation_q_w_ = value;
}
inline void TargetRelative::set_orientation_q_w(double value) {
  _internal_set_orientation_q_w(value);
  // @@protoc_insertion_point(field_set:sensor_msgs.msgs.TargetRelative.orientation_q_w)
}

// optional double orientation_q_x = 10;
inline bool TargetRelative::_internal_has_orientation_q_x() const {
  bool value = (_has_bits_[0] & 0x00000400u) != 0;
  return value;
}
inline bool TargetRelative::has_orientation_q_x() const {
  return _internal_has_orientation_q_x();
}
inline void TargetRelative::clear_orientation_q_x() {
  orientation_q_x_ = 0;
  _has_bits_[0] &= ~0x00000400u;
}
inline double TargetRelative::_internal_orientation_q_x() const {
  return orientation_q_x_;
}
inline double TargetRelative::orientation_q_x() const {
  // @@protoc_insertion_point(field_get:sensor_msgs.msgs.TargetRelative.orientation_q_x)
  return _internal_orientation_q_x();
}
inline void TargetRelative::_internal_set_orientation_q_x(double value) {
  _has_bits_[0] |= 0x00000400u;
  orientation_q_x_ = value;
}
inline void TargetRelative::set_orientation_q_x(double value) {
  _internal_set_orientation_q_x(value);
  // @@protoc_insertion_point(field_set:sensor_msgs.msgs.TargetRelative.orientation_q_x)
}

// optional double orientation_q_y = 11;
inline bool TargetRelative::_internal_has_orientation_q_y() const {
  bool value = (_has_bits_[0] & 0x00000800u) != 0;
  return value;
}
inline bool TargetRelative::has_orientation_q_y() const {
  return _internal_has_orientation_q_y();
}
inline void TargetRelative::clear_orientation_q_y() {
  orientation_q_y_ = 0;
  _has_bits_[0] &= ~0x00000800u;
}
inline double TargetRelative::_internal_orientation_q_y() const {
  return orientation_q_y_;
}
inline double TargetRelative::orientation_q_y() const {
  // @@protoc_insertion_point(field_get:sensor_msgs.msgs.TargetRelative.orientation_q_y)
  return _internal_orientation_q_y();
}
inline void TargetRelative::_internal_set_orientation_q_y(double value) {
  _has_bits_[0] |= 0x00000800u;
  orientation_q_y_ = value;
}
inline void TargetRelative::set_orientation_q_y(double value) {
  _internal_set_orientation_q_y(value);
  // @@protoc_insertion_point(field_set:sensor_msgs.msgs.TargetRelative.orientation_q_y)
}

// optional double orientation_q_z = 12;
inline bool TargetRelative::_internal_has_orientation_q_z() const {
  bool value = (_has_bits_[0] & 0x00001000u) != 0;
  return value;
}
inline bool TargetRelative::has_orientation_q_z() const {
  return _internal_has_orientation_q_z();
}
inline void TargetRelative::clear_orientation_q_z() {
  orientation_q_z_ = 0;
  _has_bits_[0] &= ~0x00001000u;
}
inline double TargetRelative::_internal_orientation_q_z() const {
  return orientation_q_z_;
}
inline double TargetRelative::orientation_q_z() const {
  // @@protoc_insertion_point(field_get:sensor_msgs.msgs.TargetRelative.orientation_q_z)
  return _internal_orientation_q_z();
}
inline void TargetRelative::_internal_set_orientation_q_z(double value) {
  _has_bits_[0] |= 0x00001000u;
  orientation_q_z_ = value;
}
inline void TargetRelative::set_orientation_q_z(double value) {
  _internal_set_orientation_q_z(value);
  // @@protoc_insertion_point(field_set:sensor_msgs.msgs.TargetRelative.orientation_q_z)
}

// optional float yaw_std = 13;
inline bool TargetRelative::_internal_has_yaw_std() const {
  bool value = (_has_bits_[0] & 0x00000100u) != 0;
  return value;
}
inline bool TargetRelative::has_yaw_std() const {
  return _internal_has_yaw_std();
}
inline void TargetRelative::clear_yaw_std() {
  yaw_std_ = 0;
  _has_bits_[0] &= ~0x00000100u;
}
inline float TargetRelative::_internal_yaw_std() const {
  return yaw_std_;
}
inline float TargetRelative::yaw_std() const {
  // @@protoc_insertion_point(field_get:sensor_msgs.msgs.TargetRelative.yaw_std)
  return _internal_yaw_std();
}
inline void TargetRelative::_internal_set_yaw_std(float value) {
  _has_bits_[0] |= 0x00000100u;
  yaw_std_ = value;
}
inline void TargetRelative::set_yaw_std(float value) {
  _internal_set_yaw_std(value);
  // @@protoc_insertion_point(field_set:sensor_msgs.msgs.TargetRelative.yaw_std)
}

// optional float std_x = 14;
inline bool TargetRelative::_internal_has_std_x() const {
  bool value = (_has_bits_[0] & 0x00002000u) != 0;
  return value;
}
inline bool TargetRelative::has_std_x() const {
  return _internal_has_std_x();
}
inline void TargetRelative::clear_std_x() {
  std_x_ = 0;
  _has_bits_[0] &= ~0x00002000u;
}
inline float TargetRelative::_internal_std_x() const {
  return std_x_;
}
inline float TargetRelative::std_x() const {
  // @@protoc_insertion_point(field_get:sensor_msgs.msgs.TargetRelative.std_x)
  return _internal_std_x();
}
inline void TargetRelative::_internal_set_std_x(float value) {
  _has_bits_[0] |= 0x00002000u;
  std_x_ = value;
}
inline void TargetRelative::set_std_x(float value) {
  _internal_set_std_x(value);
  // @@protoc_insertion_point(field_set:sensor_msgs.msgs.TargetRelative.std_x)
}

// optional float std_y = 15;
inline bool TargetRelative::_internal_has_std_y() const {
  bool value = (_has_bits_[0] & 0x00004000u) != 0;
  return value;
}
inline bool TargetRelative::has_std_y() const {
  return _internal_has_std_y();
}
inline void TargetRelative::clear_std_y() {
  std_y_ = 0;
  _has_bits_[0] &= ~0x00004000u;
}
inline float TargetRelative::_internal_std_y() const {
  return std_y_;
}
inline float TargetRelative::std_y() const {
  // @@protoc_insertion_point(field_get:sensor_msgs.msgs.TargetRelative.std_y)
  return _internal_std_y();
}
inline void TargetRelative::_internal_set_std_y(float value) {
  _has_bits_[0] |= 0x00004000u;
  std_y_ = value;
}
inline void TargetRelative::set_std_y(float value) {
  _internal_set_std_y(value);
  // @@protoc_insertion_point(field_set:sensor_msgs.msgs.TargetRelative.std_y)
}

// optional float std_z = 16;
inline bool TargetRelative::_internal_has_std_z() const {
  bool value = (_has_bits_[0] & 0x00008000u) != 0;
  return value;
}
inline bool TargetRelative::has_std_z() const {
  return _internal_has_std_z();
}
inline void TargetRelative::clear_std_z() {
  std_z_ = 0;
  _has_bits_[0] &= ~0x00008000u;
}
inline float TargetRelative::_internal_std_z() const {
  return std_z_;
}
inline float TargetRelative::std_z() const {
  // @@protoc_insertion_point(field_get:sensor_msgs.msgs.TargetRelative.std_z)
  return _internal_std_z();
}
inline void TargetRelative::_internal_set_std_z(float value) {
  _has_bits_[0] |= 0x00008000u;
  std_z_ = value;
}
inline void TargetRelative::set_std_z(float value) {
  _internal_set_std_z(value);
  // @@protoc_insertion_point(field_set:sensor_msgs.msgs.TargetRelative.std_z)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace msgs
}  // namespace sensor_msgs

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_TargetRelative_2eproto
